language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly

after_success:
  - echo "Hello! Testing Travis!!!"
  - rustup override set nightly-2019-06-18-x86_64-apple-darwin
  - rustup component add clippy --toolchain nightly-2019-06-18-x86_64-apple-darwin
  - cargo clippy
  - cargo build --verbose --all
  - cargo test --verbose --all

# global install
# install:
#   - rustup toolchain install nightly
#   - rustup component add rustfmt-preview --toolchain=nightly

# services:
# - docker

# Caching
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
