language: rust
matrix:
  include:
    - os: linux
      rust: nightly
      # skip the global install step
      install:
        - cargo install --debug --force rustfmt-nightly
      script:
        - cargo fmt -- --check
        - cargo build
        - cargo run
    - os: linux
      rust: stable
      script:
        - cargo fmt -- --check
        - cargo build
        - cargo run
  fast_finish: true

# Caching
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
