language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - echo "Hello! Testing Travis!!!"
  - cargo build --verbose --all
  - cargo test --verbose --all

# global install
# install:
#   - rustup toolchain install nightly
#   - rustup component add rustfmt-preview --toolchain=nightly

# services:
# - docker

# Caching
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
