language: rust
rust:
  - nightly
install:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
script:
  - cargo fmt -- --check
  - cargo clippy -- -D warnings
  - cargo test

# Caching
cache:
  directories:
    - /home/travis/.cargo
