language: rust
rust:
  - stable
install:
  - rustup component add rustfmt-preview
  - rustup component add clippy-preview
  - rustup show
script:
  - cargo fmt -- --check
  - cargo clippy -- -D warnings
  - cargo test

# Caching
cache:
  directories:
    - /home/travis/.cargo
