language: rust
rust:
  - nightly
install:
  - rustup override set nightly-2019-06-18-x86_64-apple-darwin # pin nightly version w/ clippy
  - rustup component add rustfmt-preview
  - rustup component add clippy --toolchain nightly-2019-06-18-x86_64-apple-darwin
  - rustup show
script:
  - cargo fmt -- --check
  - cargo clippy -- -D warnings
  - cargo test

# Caching
cache:
  directories:
    - /home/travis/.cargo
