language: rust
matrix:
  include:
    - os: linux
      rust: nightly
      # skip the global install step
      install:
        - cargo install --debug --force rustfmt-nightly
      script:
        - cargo fmt -- --check
    - os: linux
      rust: stable
      script:
        - cargo +nightly fmt -- -f
  fast_finish: true

# global install
install:
  - rustup toolchain install nightly
  - rustup component add rustfmt-preview --toolchain=nightly

# Caching
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
