language: rust
matrix:
  include:
    - os: linux
      rust: nightly
      script:
        - cargo fmt -- --check
        - echo "SUCCESS!"
    - os: linux
      rust: stable
      script:
        - cargo fmt -- --check
        - echo "SUCCESS!"
  fast_finish: true

# global install
install:
  - cargo install --debug --force rustfmt-nightly

# Caching
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
